// components/SolarExample.vue
<script setup lang="ts">
import { computed } from 'vue'

const voltage = 6
const power = 0.3
const singleBatteryCapacity = 4800
const batteries = 2

const current = computed(() => (power / voltage) * 1000) // in mA
const totalCapacity = computed(() => singleBatteryCapacity * batteries)
const chargingTime = computed(() => totalCapacity.value / current.value)
</script>

<template>
  <div class="p-4 bg-white/10 rounded-lg max-w-md mx-auto">
    <div class="space-y-2">
      <p>Solar Panel Current: {{ current.toFixed(2) }} mA</p>
      <p>Total Battery Capacity: {{ totalCapacity }} mAh</p>
      <p class="font-bold">Charging Time: {{ chargingTime.toFixed(1) }} hours</p>
      <p class="text-sm opacity-75">(Approximately {{ (chargingTime / 24).toFixed(1) }} days)</p>
    </div>
  </div>
</template>

// src/components/SolarExample.tsx
import React, { useMemo } from 'react';

export const SolarExample: React.FC = () => {
  const voltage = 6;
  const power = 0.3;
  const singleBatteryCapacity = 4800;
  const batteries = 2;

  const current = useMemo(() => (power / voltage) * 1000, []); // in mA
  const totalCapacity = useMemo(() => singleBatteryCapacity * batteries, []);
  const chargingTime = useMemo(() => totalCapacity / current, [totalCapacity, current]);

  return (
    <div className="p-6 bg-gray-800 rounded-lg max-w-md mx-auto shadow-xl">
      <div className="space-y-3">
        <p className="text-gray-300">Solar Panel Current: <span className="font-semibold text-white">{current.toFixed(2)} mA</span></p>
        <p className="text-gray-300">Total Battery Capacity: <span className="font-semibold text-white">{totalCapacity} mAh</span></p>
        <p className="text-gray-300">Charging Time: <span className="font-semibold text-white">{chargingTime.toFixed(1)} hours</span></p>
        <p className="text-sm text-gray-400">(Approximately {(chargingTime / 24).toFixed(1)} days)</p>
      </div>
    </div>
  );
};
